lib/voting_web/router.ex
defmodule VotingWeb.Router do
  use VotingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Voting.Account.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/auth", VotingWeb do
    pipe_through [:browser,:auth]
    get "/hack/:id", AuthController, :hack
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback

  end

  scope "/", VotingWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/:id", PollController, :show
  end

  scope "/poll", VotingWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/user", PageController, :user_index
    get "/new", PollController, :new
    post "/create", PollController, :create

    post "/:id/option/create", PollController, :create_option
    post "/:id/option/:id", PollController, :vote_option
  end



  # Other scopes may use custom stacks.
  # scope "/api", VotingWeb do
  #   pipe_through :api
  # get "/protected", PageController, :protected
  # end
end

lib/voting_web/templates/page/index.html.eex
<div class="container">
<%= if @current_user != nil do %>
  <section class="columns is-right">
    <div class="column is-one-fifth">
     

      <%= link "New poll", to: Routes.poll_path(@conn, :new), class: "button is-small is-primary" %>
    </div>
  </section>
  <% end %>
  <main id="poll-list-wrapper">
  <ul>
    <%= for poll <- @polls do %>
      <li> <%= link poll.text, to: Routes.poll_path(@conn, :show, poll.id), class: "button is-text is-small" %> </li>
    <% end %>
  </main>

  </ul>
</div>